### PR TITLE
LVM-426 / LVM-427: Add/edit/remove tags and tagged object filtering

### PR DESCRIPTION
**Pull request by nabeel-**
Tag index view is the main control point for tags. Modals allow for editing/showing the tagged students and tutors.

This also introduces the [DataTables](https://www.datatables.net/) jQuery plugin for pagination, search, and ordering in tables.

https://cs5500-jira.ccs.neu.edu/browse/LVM-426
https://cs5500-jira.ccs.neu.edu/browse/LVM-427

screen shot 2017-03-21 at 7 15 55 pm
screen shot 2017-03-21 at 7 16 15 pm
screen shot 2017-03-21 at 7 16 28 pm

### CODE REVIEW

**Comment by zack** [comment]
tags index -> click on a tag -> click on a student/tutor -> click back -> click x or close
expected: modal closes
actual: modal does not close

**Comment by zack** [comment]
style problem on mouseover

screen shot 2017-03-23 at 1 10 05 pm

**Comment by nabeel-** [comment]
Fixed the mouseover styling wonkiness.

The unresponsive modal was because of turbolinks. I chose to just destroy the modal off the page instead of trying to work around keeping it.

**Comment by zack** [comment]
@nabeel- are you intentionally excluding a link to the tag index view from the homepage, here?

**Review by zack — APPROVED** [review]

**Comment by nabeel-** [comment]
@zy Not intentionally, so I'll add that in

**Pull request merged**
