### PR TITLE
LVM-285 Integrate bootstrap gem for styling

### PR DESCRIPTION
**Pull request by vcantu**
Adds 'bootstrap-sass' gem and adds bootstrap import statements to the .../stylesheets/application.scss

### CODE REVIEW

**Comment by zack** [comment]
The [bootstrap-sass github page](https://github.com/twbs/bootstrap-sass) seems to have some installation instructions that aren't completed in this pr:

> Then, remove all the *= require_self and *= require_tree . statements from the sass file. Instead, use @import to import Sass files.

> Require Bootstrap Javascripts in app/assets/javascripts/application.js:

**Comment by zack** [comment]
Also looks like you need to rebase.

```
git fetch upstream
git rebase upstream/master
git push origin -f
```

**Comment by vcantu** [comment]
Rebased, fixed merge conflicts and finished bootstrap installation

**Comment by zack** [comment]
Looks good to me. Make sure when you merge it you use the "squash and merge" button, not "merge pull request." :)

Alternatively, you could squash it in git using `git rebase` if you wanna get into the nitty gritty.

Either way, it definitely isn't necessary to have all 5 commits in the final history!

**Review by zack — APPROVED** [review]

**Pull request merged**
