### PR TITLE
LVM-504: Disable user account creation

### PR DESCRIPTION
**Pull request by avnighael**

### CODE REVIEW

**Comment by avnighael** [comment]
@akshayhonap619

**Review by kmcarol26 — CHANGES_REQUESTED** [review]
This is merging master to disable-account-creation. Please fix this

**Review by kmcarol26 — CHANGES_REQUESTED** [review]
This is merging master to disable-account-creation. Please fix this

**Comment by kmcarol26** [comment]
Looks good now.

**Pull request merged**
