### PR TITLE
LVM-412 updated Affiliate Show View with bootstrap

### PR DESCRIPTION
**Pull request by jlally21**
https://cs5500-jira.ccs.neu.edu/browse/LVM-412

### CODE REVIEW

**Comment by zack** [comment]
screen shot 2017-03-14 at 4 28 17 pm

**Review by zack — CHANGES_REQUESTED** [review]
doesn't have the same width/alignment as other show views.

**Comment by jlally21** [comment]
@zack  check out the width/alignment changes when you get a chance

**Review by zack — APPROVED** [review]
In line with our other show views, but **I think this (and our other show views) will need more work in the future**. As it is, the spacing is confusing and muddled. I think we should either focus on having the label to the left (instead of above) or we should have more vertical spacing. As it is, each value is closer to the key below it (not its key) than the key above it (its key).

**Pull request merged**
